Fix: WebInspector.ElementsPanel is undefined during the initial load because it loads lazily via XHR
It's not ready, it breaks DevTools:
    Uncaught TypeError: undefined is not a function Panel.js:314